name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
        id-token: write   # This is required for requesting the JWT
        contents: read    # This is required for actions/checkout
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "build"
  build:
    # the environment name
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/staging' && 'staging') || 'dev' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: root_module/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{vars.IAM_ROLE}}
          aws-region: us-east-1
          role-session-name: login-session-by-github-actions

      # Runs a set of commands using the runners shell
    #   - name: Print AWS Identity
    #     run: |
    #       aws sts get-caller-identity

      - name: Terraform commands
        run: |
            terraform init
            terraform plan -input=false -var-file=${{vars.ENVIRONMENT_STAGE}}.tfvars
        # terraform apply -auto-approve -var-file=ENVIRONMENT_STAGE.tfvars